set(CTEST_PROJECT_NAME "msi")
set(CTEST_NIGHTLY_START_TIME "07:00:00 EST")

set(CTEST_DROP_METHOD "cp")
set(CTEST_DROP_LOCATION "/fasttmp/wtobin/nightly/cdash/${CTEST_PROJECT_NAME}")
set(CTEST_DROP_SITE_CDASH FALSE)
