PETSC_DIR=/fasttmp/seol/petsc-3.5.4-complex
PETSC_ARCH=openmpi1.6.5
PREFIX=/fasttmp/seol/openmpi-gcc4.4.5-install
cmake .. \
  -DCMAKE_C_COMPILER="/usr/local/openmpi/latest/bin/mpicc" \
  -DCMAKE_CXX_COMPILER="/usr/local/openmpi/latest/bin/mpicxx" \
  -DCMAKE_Fortran_COMPILER="/usr/local/openmpi/latest/bin/mpif90" \
  -DCMAKE_C_FLAGS=" -g -O2 -DDEBUG -I$PETSC_DIR/include" \
  -DCMAKE_CXX_FLAGS=" -g -O2 -DDEBUG -I$PETSC_DIR/include" \
  -DCMAKE_Fortran_FLAGS="-fpic "\
  -DSCOREC_INCLUDE_DIR=$PREFIX/include \
  -DSCOREC_LIB_DIR=$PREFIXl/lib \
  -DZOLTAN_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libzoltan.a" \
  -DPARMETIS_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libparmetis.a" \
  -DMETIS_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libmetis.a" \
  -DENABLE_SIMMETRIX=OFF \
  -DSIM_MPI=openmpi165-ib \
  -DSIMMETRIX_INCLUDE_DIR=/net/common/meshSim/latest/include \
  -DSIMMETRIX_LIB_DIR=/net/common/meshSim/latest/lib/x64_rhel5_gcc41 \
  -DENABLE_PETSC=ON \
  -DPETSC_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DPETSC_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DHDF5_INCLUDE_DIR="$PETSC_DIR/$PETSC_ARCH/include" \
  -DHDF5_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DENABLE_TRILINOS=OFF \
  -DTRILINOS_INCLUDE_DIR="/fasttmp/seol/openmpi-gcc4.4.5-install/include" \
  -DTRILINOS_LIB_DIR="/fasttmp/seol/openmpi-gcc4.4.5-install/lib" \
  -DLAPACK_LIB_DIR="$PETSC_DIR/$PETSC_ARCH/lib" \
  -DBOOST_LIB_DIR="/fasttmp/seol/openmpi-gcc4.4.5-install/lib" \
  -DSTDCPP_LIBRARY="/usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a" \
  -DNETCDF_LIBRARY="$PETSC_DIR/$PETSC_ARCH/lib/libnetcdf.a" \
  -DENABLE_COMPLEX=ON \
  -DENABLE_TESTING=OFF \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INSTALL_PREFIX=$PREFIX

